import './globals.css'
import Header from '@/app/components/header'
import { Mulish } from 'next/font/google'
import Footer from './components/footer'

const mulish = Mulish({ subsets: ['latin'] })

export const metadata = {
  title: 'WatcFlix',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Header></Header>
        {children}
        <Footer></Footer>
        </body>
    </html>
  )
}
